# action.yml
name: 'draft release note'
description: 'Create a draft release note from a github repo project'
inputs:
  project-column-name:  # id of input
    description: 'the column name in the github projects, e.g. stage'
    required: true
  release-tag:  # id of input
    description: 'the git tag for the draft release, e.g. v1.0.0'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project-column-name }}
    - ${{ inputs.release-tag }}
