on:
  workflow_dispatch:
    inputs:
      ProjectsColumnName:
        description: 'target column name in github projects (e.g. stage)'
        required: true
      Tag:
        description: 'the tag you want to use in this release (e.g. v1.0.0)'
        required: true

jobs:
  release_job:
    runs-on: ubuntu-latest
    name: Create a draft release
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Execute the command
        uses: ./ # Uses an action in the root directory
        id: step_release
        with:
          branch-name: ${{ steps.extract_branch.outputs.branch }}
          project-column-name: ${{ github.event.inputs.ProjectsColumnName }}
          release-tag: ${{ github.event.inputs.Tag }}
      # Use the output from the `step_release` step
      - name: Get the output time
        run: echo "The time was ${{ steps.step_release.outputs.tag }}"
