on:
  workflow_dispatch:
    inputs:
      ProjectsColumnName:
        description: 'Projects Column Name'
        required: true
      Tag:
        description: 'The tag you want to use in this release'
        required: true

jobs:
  release_job:
    runs-on: ubuntu-latest
    name: Create a draft release
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute the command
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: '${{ github.event.inputs.ProjectsColumnName }} ${{ github.event.inputs.Tag }}'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
